### ISSUE TITLE
Use getInverterInfo

### ISSUE THREAD

**Issue by pieterzen** [thomascys/solaxcloud#3]
Hi,  
Great that you've shared your solution to the Solax API debacle. 
I've been trying to a Rest call in HA but the archaic sessionId stuff is not supported in HA. I will try your plugin, but I already have a suggestion. Instead of DailyInfo (which is huge) you can use the following endpoint:
`http://www.solaxcloud.com:6080/proxy/mysite/getInverterInfo?siteId=<SiteId>&tokenId=<tokenId>`

This call only returns the current data for your inverter. You need a Site, and then the siteid which you can find inspecting the link to your site.

**Comment by thomascys** [comment]
Just tested that endpoint. This is amazing and would mean an enormous performance boost for this integration. I'll try to rewrite it one of the coming days.
Thanks again for this great suggestion! I wasn't aware of that endpoint.

**Comment by pieterzen** [comment]
I've already done that and tested it. If you can give me permissions I can push a branch so you can have a look too.

**Comment by pieterzen** [comment]
[solaxcloud.zip](https://github.com/thomascys/solaxcloud/files/4587292/solaxcloud.zip)

**Comment by thomascys** [comment]
Feel free to provide a pull request and then we can move on from there

**Comment by pieterzen** [comment]
Took me a while to work that out :) Don't work with external repo's that much

**Comment by thomascys** [comment]
Reviewed your pull request and merged it. I've also added new installation instructions.

Thanks for taking the time and share this improvement!
